name: testing github actions

on:
  push:

jobs:
  test-job:
    runs-on: ubuntu-20.04
    steps:
      - name: print something
        run: echo ABC
      - name: My first step - check out repository
        uses: actions/checkout@v4
      
      - name: Use local hello-world-action
        uses: ./.github/actions/my-action